version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fusionpact_net

  backend:
    build: ./backend
    container_name: fusionpact-backend
    ports:
      - "8000:8000"
    volumes:
      - user_data:/app/app/data
    networks:
      - fusionpact_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - fusionpact_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - fusionpact_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - fusionpact_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - fusionpact_net

networks:
  fusionpact_net:

volumes:
  user_data:
  grafana-storage:
